### PR TITLE
Make Chunk available to torch.tensor 

### LINKED ISSUE #16: Error with latest version of chunks in cpic utils.py
I'm getting an error message from chunks when doing detection in array.take (line 25). I think my code must be confusing take from numpy and pytorch.
**Error message:** TypeError: take() missing 1 required positional arguments: "index"

I didn't manage to find a solution besides changing to the old version of utils.py

### PR DESCRIPTION
**Pull request by lijunzh**
Fix #16 

Add a `torch.Tensor` version of `chuck()` function.

### CODE REVIEW

**Comment by lijunzh** [comment]
@miguelj-neves Can you check if the PR fixes your issue?

**Comment by miguelj-neves** [comment]
@lijunzh this solved my issue

**Comment by lijunzh** [comment]
Great. I will merge it then.

**Comment by lijunzh** [comment]
@miguelj-neves The changes has been merged into master. Please git it a try.

**Pull request merged**
